### ISSUE TITLE
Spurious E301 for nested function definitions

### ISSUE THREAD

**Issue by walkerh** [PyCQA/pycodestyle#28]
Simple nested functions without preceeding blank line are not a violation of PEP 8. It is up to the human to decide readability in this case.

pep8-0.6.1 will emit errors in cases where an extra blank line is not required or appropriate.

Example code, pep8_bug.py:

    """Demonstrate bug"""

    def safe_accessors(dictionary=False):
        """simplified from complex test code..."""
        if dictionary:
            _setattr, _getattr, _delattr = setitem, getitem, delitem
            def _hasattr(_dict, value):
                return value in _dict
        else:
            _setattr, _getattr, _delattr, _hasattr = (
                setattr, getattr, delattr, hasattr
            )
        return _setattr, _getattr, _delattr, _hasattr

pep8 output:

    pep8_bug.py:9:9: E301 expected 1 blank line, found 0

The correct output is to be silent (or at most emit a silence-able warning).

Reference: "PEP 8" / "Code lay-out" / "Blank Lines"

**Comment by memeplex** [comment]
I use nested functions and the current behavior requires (to conform) arbitrary empty lines that are often very misleading about the logic divisions inside a function.

If we can reach and agreement about which is the desired new behavior here, I will gladly implement a fix for this.

My proposal is to keep the current E301 definition *except for nested functions/classes definitions*. With nested functions/classes I mean functions/classes that are local to another function, not functions/classes nested inside a class definition.

What do you think?

**Comment by azag0** [comment]
A temporary dirty fix would be for E301 to be included in the noqa-ignorable warnings. I don't think nested functions are that frequent and having one "# noqa" comment is still much more acceptable to me than having a blank line that does not make any sense.

**Comment by sigmavirus24** [comment]
So I just re-read some of this discussion, and I'd like to point out one statement that has gone unchallenged and is wrong on its face:

> We can assume that every class definition which is indented and every function definition which is indented more than 2 levels are nested definitions.

I've maintained and contributed to several projects that use the concept of optional drivers (or adapters, or whatever you want to call it) where something is defined like so:


```py
try:
    import module
except ImportError
    module = None


if module is None:
    class ModuleDriver:
         def some_method(self, param, param):
              # etc.

else:
    class ModuleDriver:
         def some_method(self, param, param):
```

This is a top-level definition. It is not a nested definition. It is a conditional definition. Anything that attempts to fix this should be mindful of this. Also keep in mind that further *guesses* at what indentation level "must" mean semantically can be further disproven by other nested conditionals based on definition.

**Comment by memeplex** [comment]
@azag0 I didn't know about any noqa-ignorable list. Is that for flake8 or for pep8?

**Comment by azag0** [comment]
Well, I don't know whether there is an explicit list somewhere, but I was referring to #180

**Comment by sigmavirus24** [comment]
Each check individually chooses to observe NOQA or not.

**Comment by warsaw** [comment]
I just ran across this issue.  My own quasi-authoritative take on this is that nested functions and classes (and the methods within those classes) do not necessarily conform to the same blank line rules as top-level functions and classes.

Nested functions and classes are a bit of a special case, they are infrequent, and typically added for convenience rather than public functionality.  E.g. you might define a sort function inline, or you might have a little mock class inside of a test.  Since these aren't public, module global names, succinctness is acceptable and artificial blank lines can disrupt the flow.  It's also entirely acceptable to use comments to visually separate such nested functions and classes from the surrounding code.

Ultimately, I think E301 isn't appropriate for nested functions and classes.

**Comment by memeplex** [comment]
Well I'm about to write a patch for myself, and maybe for you. So I would like to know: if I adapt  https://github.com/attilaolah/pep8/commit/f0d47409287998f89931bfd1dc7cf9af34b28819 so that it throws a new error code as requested by @florentx, would it be good enough for you? This new error should be enabled or disabled by default?

**Comment by memeplex** [comment]
Well, I see https://github.com/attilaolah/pep8/commit/f0d47409287998f89931bfd1dc7cf9af34b28819 has many issues. I will try to fix the nested-in-function detection logic.

**Comment by memeplex** [comment]
Please, tell me what do you think while this is still fresh in my mind.

**Comment by memeplex** [comment]
Hi there, is anything else I can do to get my patch pulled in? It was reviewed favourably, a further ok test was requested but I explained why I think it doesn't make much sense here. I have also found an unrelated bug in the affected function (see the pr discussion). Please let me know if something is missing and I will do it asap.
