### ISSUE TITLE
Indentation checkers should not be active on code inside triple-quotes

### ISSUE THREAD

**Issue by posborne** [PyCQA/pycodestyle#45]
If I have a multi-line string (in triple quotes), I don't believe that pep8 should be analyzing the contents for indentation problems and the like.  This code may very well be not-python and, as such, need not comply to pep8.  It might be nice (though I am not certain of how easy) to treat docstrings different from other block quotes as there are guidelines on docstrings in PEP 257: http://www.python.org/dev/peps/pep-0257/

**Comment by maxkoryukov** [comment]
@florentx @myint 

> `# noqa` on the last line of the docstring.

Is it workaround, or final solution? I would like to use docstrings for documentation purposes, and I want to have whitespaces, tabulation and other stuff there, out of the box, without sane limitations. Currently it is looks like `pep8` poke its nose in where it didn't belong (IMO).

For example, I want to place markdown into docstrings, bcz doc-parser supports it, and I like it. But `flake8` raise an issue on my docstrings, because there are trailing whitespaces (_they are required in my cases_)

BTW: PyCharm **can not** remove trailing whitespaces in docstrings automagically. It requires some tunings/dancing/virgin-blood/moonlight to provide this functionality. Sad, because people told, that PyCharm - is a _decent_ IDE for python..

**Comment by sigmavirus24** [comment]
> Is it workaround, or final solution?

It is something you can use _today_. So in a way it's both.

> Currently it is looks like pep8 poke its nose in where it didn't belong (IMO).

I disagree, but that's *my* opinion.

> there are trailing whitespaces (they are required in my cases)

That's unfortunate

> BTW: PyCharm can not remove trailing whitespaces in docstrings automagically.

That's surprising and disappointing but not relevant here.

**Comment by maxkoryukov** [comment]
@sigmavirus24 thank you for reply. I will cry and eat this cactus ))

**Comment by gyermolenko** [comment]
>> Is it workaround, or final solution?

> It is something you can use today. So in a way it's both.

@sigmavirus24 Could you please clarify resolution on this issue?
Personally I can't understand why it is closed (just my opinion, no hard feelings)

**Comment by sigmavirus24** [comment]
> > > Is it workaround, or final solution?
> 
> > It is something you can use today. So in a way it's both.
> 
>  Could you please clarify resolution on this issue?

- `# noqa` will continue to skip this warning. (hence the joke about finality)
- `# noqa` support was added providing an escape hatch for folks who want to opt out of this behaviour
- Florent was quite explicit that at the time of their writing, this was not okay per PEP-0008. I haven't bothered to confirm that it still is given the infuriating fluidity of that document (revisions days apart will conflict). And this tool serves, to the best of its ability, provide checks that hold to the document. So, in a way, at the time of implementation this was the correct behaviour provided the mission statement of the tool. It may no longer be and we can open a new issue to track that and potentially fix it.

**Comment by kaddkaka** [comment]
Is the intention to keep this behavior or "fix" it? Where should the `#noqa` magical comment be but? I'm not a fan of `#noqa` since it's a short abbreviation and without prior knowledge it's hard to know what it is.
