### ISSUE TITLE
E111 should fire when indented with 8 spaces

### ISSUE THREAD

**Issue by rhysd** [PyCQA/pycodestyle#490]
- Code

```python
if true:
        print('hello')
```

- Command

```
$ pep8 code.py
```

- Output

Nothing (no error and warning)

-----

PEP8 says

> Use 4 spaces per indentation level.

So, I think the `print('hello')` line should be illegal.

- Environment
  - Python 3.5
  - pep8 1.7.0
  - OS X 10.11.4

**Comment by sigmavirus24** [comment]
The code for this check specifically says:

```
Use 4 spaces per indentation level.

For really old code that you don't want to mess up, you can continue to
use 8-space tabs.
```

In other-words, 8 spaces will not generate a warning. That said, I had plans to allow users to specify a custom-indentation level to strictly enforce (https://gitlab.com/pycqa/flake8-custom-indent) but never got around to it.

I would say this bug report is invalid given this is something intentional.

**Comment by rhysd** [comment]
Hmm... OK, I'll consider other more strict checker.
