### ISSUE TITLE
Update pep8 RTD to point to pycodestyle

### ISSUE THREAD

**Issue by IanLee1521** [PyCQA/pycodestyle#602]
From https://github.com/PyCQA/pycodestyle/issues/466#issuecomment-260721352

> Also, the note on http://pep8.readthedocs.io/en/release-1.7.x/ (where the "read documentation" points to) mentions the rename but doesn't provide links to either PyPI or RTD for the new name, both of which would be helpful.

**Comment by JonathanDensil** [comment]
@IanLee1521 I am new to contributing to github projects. I read the contributing doc and am guessing I would first have to fork this project and then install virtualenv. Would it be possible for you to walk me through the process in resolving this issue please?

**Comment by IanLee1521** [comment]
Hi @JonathanDensil, thanks for your interest!

For forking, I would take a look at the [Forking Projects](https://guides.github.com/activities/forking/) guide.

For Virtualenv, I would take a look at their main documentation, specifically the [Basic Usage](http://docs.python-guide.org/en/latest/dev/virtualenvs/#basic-usage) section.

**Comment by JonathanDensil** [comment]
Hi @IanLee1521 , I successfully forked the project and installed virtualenv, but I am using windows 10 and when I tried to run `source venv/bin/activate` it gave me an error saying:
`source : The term 'source' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ source venv/bin/activate
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (source:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`
I believe this is because 'source' is a linux command. Just running 'activate' does not give an error, but no result is shown either. How would I activate the virtual environment on windows 10? 

Interestingly (I'm not sure if this is right...):
pycodestyle\venv
pycodestyle\pycodestyle-venv
pycodestyle\pycodestyle-venv\Scripts\ENV

All of the paths have the same files in them, they look identical. That means that there is an activate and an activate.bat in each Scripts folder. I also don't have a bin folder (I suspect that bin is also only on linux)

**Comment by sigmavirus24** [comment]
@JonathanDensil Did you read virtualenv's documentation on this? http://virtualenv.readthedocs.io/en/stable/userguide/#activate-script

**Comment by JonathanDensil** [comment]
Ahh, I was using powershell and it required an execution policy. It works on the cmd. Thank you for your help. Now, onto resolving this issue. What would be the procedure be in doing so?

**Comment by IanLee1521** [comment]
Hi @JonathanDensil -- The typically workflow on GitHub, which we use, is:

1. Fork the repo
2. Edit the file(s) you need for your change
3. Commit and push to your fork
4. Submit a pull request back to this repo (the `origin`)

GitHub has some decent guides on these topics : 

- https://guides.github.com
- https://try.github.io
- https://help.github.com/articles/creating-a-pull-request/
- https://guides.github.com/activities/hello-world/

**Comment by JonathanDensil** [comment]
Hi @IanLee1521, well actually I was referring to this specific issue. I believe that you are referring to making a link for the words under the note section: pep8 to https://www.python.org/dev/peps/pep-0008/; and pycodestyle to https://pypi.python.org/pypi/pep8/1.7.0. If this is the case, I couldn't find the file to edit and add those links in the code base. The intro.rst file under docs doesn't include the note so I couldn't edit that section. Where would I be able to find that section?
![image](https://cloud.githubusercontent.com/assets/20889158/21281677/b5aa0a32-c3bc-11e6-905f-86c8642ad7d1.png)

**Comment by IanLee1521** [comment]
I want to encourage you to poke around a bit on your own before just giving everything away, but the gotcha there is a bit odd. That link is to the `release-1.7.x` version of the docs, so you need to switch to that branch: 

- https://github.com/PyCQA/pycodestyle/blob/release/1.7.x/docs/index.rst

**Comment by JonathanDensil** [comment]
Ohh I see. I have downloaded the GitHub for Windows and have forked the repository. I have been doing some messing around with a small repository that I made for myself. Not to be hasty or anything, I am just really excited to have my first contribution to a public open source project, just so that I can get the ball rolling and contribute more. So, if I add the link to the index.rst in my forked repository and then commit and push it to the `release-1.7.x` branch in my forked repository and then submit a pull request, would that be acceptable?

**Comment by JonathanDensil** [comment]
Hi @IanLee1521, I edited the index.rst document, committed the changes to my fork and then created a pull request back to the original repository. It says that all checks have failed, but I presume that it was because index.rst is not a python file. Please review my pull request.

**Comment by JonathanDensil** [comment]
Hi @sigmavirus24 and @IanLee1521, I corrected the problem with the previous commit, changed the link addresses and abided by the line length guide as requested by sigmavirus24 in his review of my previous commit. I hope that I have done it right this time. Thank you, please review.

**Comment by hugovk** [comment]
I think this issue can now be closed; https://github.com/PyCQA/pycodestyle/pull/606 has been merged which added this to https://pep8.readthedocs.io/en/release-1.7.x/: 

![image](https://user-images.githubusercontent.com/1324225/31394298-a464dbd4-ade6-11e7-890b-aa407c75f63a.png)
