### ISSUE TITLE
The whl and egg package has pep8.py

### ISSUE THREAD

**Issue by okuta** [PyCQA/pycodestyle#745]
When I install pycodestyle by pip, `pep8.py` was overwritten by pycodestyle installer.
Is it correct behavior?

I read #544 . This issues conclusion is following one.
> All that said, I think we're all in agreement that we shouldn't break the pep8 package or CLI, so I'm closing this.

The following two packages have a `pep8.py` (version 1.7.1). 
- `pycodestyle-2.4.0-py2.py3-none-any.whl`
- `pycodestyle-2.4.0-py3.6.egg`

I can use `pip install --no-binary :all: pycodestyle` to avoid installing `pep8.py` because `pycodestyle-2.4.0.tar.gz` has no `pep8.py` .

I want to use pycodestyle and *old* pep8 in same environment. I know workaround about this problem now. But, it was little bit complicated problem.

P.S.
I hope that all software uses pycodestyle instead of pep8 . But, some software still uses pep8. Thanks!

**Comment by mattburgess** [comment]
How does the whl/egg get pep8.py included?  I ask because pep8.py appears to have the same bug as pycodestyle.py had a while ago (https://github.com/PyCQA/pycodestyle/issues/728).  flake8-3.6.0 now pulls in pycodestyle-2.4.0 so I thought my Python-3.7 linting woes would be over. Alas, pep8.py is showing the same error:
```
lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
```
I don't particularly care if pep8.py is removed or simply receives the same fix as pycodestyle.py did.  I'd raise a PR myself, but its inclusion is sufficiently magic to me to make that unlikely.

**Comment by davemichels** [comment]
A workaround for now is to `pip uninstall pycodestyle` then `pip install git+https://github.com/PyCQA/pycodestyle.git@2.4.0'.` The version in the repository does not include pep8.py.

**Comment by sigmavirus24** [comment]
2.4.0 can't be re-released. 2.5.0 was released and should not have pep8 in it any longer.

**Comment by okuta** [comment]
Thank you very much!
