### ISSUE TITLE
Ignore #! for E265

### ISSUE THREAD

**Issue by bje-** [PyCQA/pycodestyle#757]
This test case produces error E265 and shouldn't:

```
# -*- coding: utf-8 -*-
#!/usr/bin/env python
```

It seems that pycodestyle can handle `#!` on line 1, but not if there are other comments first.

**Comment by hoylemd** [comment]
The shebang must always be the first thing in the file, since it's actually a magic number used for `exec()` interpreters to know what to do with the shebang line.

So in your example, that isn't a shebang line at all, it's just a weird comment.

Swap around the shebang line and the coding line and you're good 👍

**Comment by bje-** [comment]
Thanks, that's what I understood, too, but wondered if the Linux kernel had got more sophisticated in how it dealt with `#!`.
