### ISSUE TITLE
Don't emit line-too-long warning when word in longer than maximum linewidth.

### ISSUE THREAD

**Issue by anntzer** [PyCQA/pycodestyle#817]
Ever since #224 has been fixed, long "words" (in practice, URLs) are exempted from the line-too-long warning *if they are the only item on their line*.  However, there are some other cases where it is impractical to split a line before an URL.  In particular, this includes rst hyperlink targets (http://docutils.sourceforge.net/docs/user/rst/quickref.html#hyperlink-targets), which take the form
```
This is `some text`_.

.. some text: https://etc.
```
or the anonymous form
```
This is `some text`__.

__ https://etc.
```

Obviously, one can't expect pycodestyle to parse rst, but as a partial fix, it would still be nice to not emit the line-too-long warning *if a single word is longer than the maximum linewidth, minus the current indentation* (because most often the current indent is set by the surrounding code/text, so one doesn't have the choice anyways).  (This will fail to suppress the warning if the word in itself is shorter than the linewidth, but the full construct with the leading text is longer; still I'm happy with that limitation.)

**Comment by sigmavirus24** [comment]
In the first case you can actually do:

```rst
.. some text:
    https://....
```

And the anonymous form tends to create other problems with sphinx-doc. In short, this is the least surprising behaviour in my opinion, especially when you consider that all the doc tools make it easy to shoe-horn their syntax into this format.

**Comment by anntzer** [comment]
Thanks for the suggestion.  Upon checking, even the anonymous form allows
```
__
    https://...
```
which I guess is fine.

Feel free to close the issue if the above-mentioned suggested fix does not inspire you :)

**Comment by sigmavirus24** [comment]
It doesn't inspire me to do the work myself. That said, I think it's a reasonable algorithm that would make people's lives better. The goal of the tool isn't to punish folks for being reasonable but instead to help enforce a team's chosen style. If someone wanted to send a pull request for this I would review it and merge it.

**Comment by tony** [comment]
I'm being plagued by this: https://github.com/cihai/cihai/blob/8dab033/cihai/conversion.py#L60

```
cihai-qCm47FJK ❯ flake8
./cihai/conversion.py:60:89: E501 line too long (107 > 88 characters)
```

**Comment by sigmavirus24** [comment]
@tony Please read the later comments on this. Three is a valid RST/Sphinx work-around that triggers the avoidance of this.

**Comment by tony** [comment]
>  Three is a valid RST/Sphinx work-around that triggers the avoidance of this.

@sigmavirus24 Sorry! I don't understand the conversation or why this was closed. Can you explain them based on this example so I / others can see the work-around?

I'm a bit concerned by the terminology of "valid RST" and this issue being closed.

The reason why is it feels a bit odd that a URL of reStructuredText, inside of a docstring, is being linted to begin with. (I'm a bit murky on line length being recognized in comments to begin with, but it's another topic) Wouldn't the principle of least astonishment be a guiding light? It feels odd to have to use two different styles of RST: one for '.py' files to satisfy linters, and another for .rst files.

Let's assume https://github.com/cihai/cihai/blob/8dab033/cihai/conversion.py#L60, or a minimum viable example of this:

```python
"""
Any other change upon @ `conversion.py @9227813`_.

.. _conversion.py @9227813: https://bitbucket.org/lost_theory/ltchinese/raw/9227813/ltchinese/conversion.py
"""
```

What would be the workarounds?

Can we let other people chime in later in this issue to see if they agree the solution is satisfactory to them?

**Comment by sigmavirus24** [comment]
@tony This is closed because it was resolved and should have already been closed by the time you commented. Based on your example, and thus recreating what was said above:

```py
"""
Any other change upon @ `conversion.py @9227813`_.

.. _conversion.py @9227813:
     https://bitbucket.org/lost_theory/ltchinese/raw/9227813/ltchinese/conversion.py
.. _another link:
     https://example.com
"""
```

If I remember correctly, we didn't use to consider docstrings but PEP 257 argued for a 72 character line-length and people wanted us to check the line-length but instead of making the line-length 72, it was kept at 79 (the old recommendation from PEP 8). That was already generous, when it was pointed out that links would need to be longer than any line-length check, the affordance of having it on its own line (with any amount of preceding indentation, same with comments) would skip the check.

> It feels odd to have to use two different styles of RST: one for '.py' files to satisfy linters, and another for .rst files.

Well the style works in both cases and (in my opinion) is more readable anyway. 



> Second, the linting ignore statement on the multiline doc doesn't work as I'd expect (maybe it's just me!). I'd expect `""" # flake8: noqa: E501` to apply to the whole multiline block.

Except that `flake8: noqa` is meant as file-wide comment and Flake8 ignores it with an error code or anywhere except at the start or end of the file. Additionally, `flake8: noqa` is only observed by Flake8, not pycodestyle. And pycodestyle only understands `# noqa`, not Flake8's custom `# noqa: E501` syntax.

> Can we let other people chime in later in this issue to see if they agree the solution is satisfactory to them?

You seem to be the first person to not understand the solution as discussed prior to your first comment. Others seem to be satisfied with the solution. Even if they disagree, the issue isn't locked and we don't use a bot to auto-lock conversations unlike some projects. In other words, anyone could chime in. That said, this project is pretty stable at this point with the occasional update for whatever new syntax the core developers have added this month. I doubt there's going to be anyone willing to bother updating functionality that has been satisfactory for _years_.
