### ISSUE TITLE
When a reserved keyword appears in a f-string, the error only shows as `[flake8] E999: SyntaxError: invalid syntax` on the first line

### ISSUE THREAD

**Issue by otakutyrant** [PyCQA/pycodestyle#944]
For example:

```
#!/usr/bin/env python

print(f"""{try}""")
```

I used flake8 as a checker in neovim and it complained `[flake8] E999: SyntaxError: invalid syntax` in the first line.

I think that the error could be more readable, like showing reserved keyword used in f-string and locating the specific position.

**Comment by FichteFoll** [comment]
This repository is for pycodestyle only. flake8 is maintained [on gitlab](https://gitlab.com/pycqa/flake8/)

**Comment by asottile** [comment]
as I said in the pyflakes issue that you also made, this isn't a problem with flake8, pycodestyle, or pyflakes but a problem with cpython itself and how it reports error positions for problems inside of f-strings

fortunately, this is fixed in python3.9: https://github.com/PyCQA/pyflakes/issues/553#issuecomment-639268457
