### ISSUE TITLE
E302 with @overload

### ISSUE THREAD

**Issue by Dreamsorcerer** [PyCQA/pycodestyle#999]
I'm getting E302 when using overloads like:
```
@overload
def foo(args...,
            more_args...):
    ...
@overload
def foo(args...,
            more_args...):
    ...
def foo(args, more_args...):
    do_something()
```

This seems to be the recommended layout for overloads:
https://docs.python.org/3/library/typing.html#typing.overload

I do see it mentioned here: https://github.com/PyCQA/pycodestyle/issues/908#issuecomment-619163483
But, it seems the changes made are not working. If I put the `...` on the same line, as in that comment, then I get both E703 and E302.

**Comment by sigmavirus24** [comment]
> This seems to be the recommended layout for overloads:
> https://docs.python.org/3/library/typing.html#typing.overload

I don't read that as a recommendation for style. It's not required by mypy and it looks to be without newlines likely only because it's part of a docstring and it makes the source code look cleaner - not because that's how someone intended the style to be.

---

https://github.com/PyCQA/pycodestyle/pull/927/files seems to cover testing for this so the fact that you're getting an error makes me suspicious that you aren't on the right version. You didn't provide the version information, so that's my natural assumption until you can verify otherwise

**Comment by asottile** [comment]
from pycodestyle's perspective you're allowed to omit the newlines if they are oneliner functions -- since your `...` is indented and on a different line it won't count as a oneliner

**Comment by Dreamsorcerer** [comment]
As I mentioned, moving the `...` to the same line just adds a second error, without resolving the first.

The code I'm talking about can't go on a single line as the arguments would push it over the line length, therefore the arguments are wrapped across 2 lines. It is still a one-liner in terms of logical lines (rather than physical lines).

**Comment by asottile** [comment]
E703 is off by default, so you've opted into the behaviour you're unhappy about

if it doesn't fit the oneliner exclusion then it isn't eligible for skipping E302
